apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seeds-claim0
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
status: {}
