import sys
import os
import random
import numpy as np
import mathutils.noise
import bpy  # import may be flagges as error by IDEs, bpy is present as a dependency at runtime


# Initialize the seeded random functions used within blender with a deterministic random value generated by the seed service
def patch_random(seed):
    random.seed(seed)
    np.random.seed(seed)
    mathutils.noise.seed_set(seed)

# retrieve job from orchestrator script and seperate the job information


def read_job():
    line = sys.stdin.readline().strip()
    if not line:
        return None

    parts = line.split()  # split job information into its parts
    if len(parts) != 5:
        print(f"ERROR: malformed job line: {line}", flush=True)
        return None

    if parts[0] != "JOB":
        print(f"ERROR: expected 'JOB', got: {parts[0]}", flush=True)
        return None

    # unpack fields
    _, input_file, output_file, worker_seed_str, seed = parts
    worker_seed = int(worker_seed_str)
    return input_file, output_file, worker_seed, seed


# The main function that waits for jobs and keeps the blender instance permanently open, spawning user script instances for each job
if __name__ == '__main__':
    # Read user script path from the args
    user_script_path = sys.argv[sys.argv.index("--f")+1]
    while True:  # wait for job from orchestrator
        job = read_job()  # parse job information
        if job is None:
            continue

        inputFile, outputFile, workerSeed, seed = job

        # patch prng generators with worker seed to ensure deterministic behavior
        patch_random(workerSeed)

        # store output path variables
        base = os.path.basename(outputFile)  # filename.type
        base_no_ext = os.path.splitext(base)[0]  # filename
        out_dir = os.path.dirname(outputFile)  # /output/

        # write necessary info for user script into globals
        wrapper_globals = {
            "__name__": "__main__",
            "__file__": user_script_path,
            "INPUT_FILE": inputFile,
            "OUTPUT_PATH": out_dir,
            "OUTPUT_FILE": base_no_ext,
        }

        # load and run the user script from the specified path, providing the global information
        with open(user_script_path, 'r') as f:
            code = compile(f.read(), user_script_path, 'exec')
            exec(code, wrapper_globals)

        # After user script runs
        # retrieve the generated files
        files = [
            f for f in os.listdir(out_dir)
            if f.startswith(base_no_ext)
        ]

        # for each file generated, return a completion message with its path and seed to the orchestrator
        for f in files:
            actual_path = os.path.join(out_dir, f)
            print(f"RESULT {actual_path} {seed}", flush=True)
