// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: metadata.proto

package metadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Seed                  string                 `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	SceneSeed             string                 `protobuf:"bytes,2,opt,name=scene_seed,json=sceneSeed,proto3" json:"scene_seed,omitempty"`
	CreationTimestamp     int64                  `protobuf:"varint,3,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	Filetype              string                 `protobuf:"bytes,4,opt,name=filetype,proto3" json:"filetype,omitempty"`
	Filehandle            string                 `protobuf:"bytes,5,opt,name=filehandle,proto3" json:"filehandle,omitempty"`
	ScanSeed              string                 `protobuf:"bytes,6,opt,name=scan_seed,json=scanSeed,proto3" json:"scan_seed,omitempty"`
	ScanFilehandle        string                 `protobuf:"bytes,7,opt,name=scan_filehandle,json=scanFilehandle,proto3" json:"scan_filehandle,omitempty"`
	ScanFiletype          string                 `protobuf:"bytes,8,opt,name=scan_filetype,json=scanFiletype,proto3" json:"scan_filetype,omitempty"`
	ScanCreationTimestamp int64                  `protobuf:"varint,9,opt,name=scan_creation_timestamp,json=scanCreationTimestamp,proto3" json:"scan_creation_timestamp,omitempty"`
	PassedQc              bool                   `protobuf:"varint,10,opt,name=passed_qc,json=passedQc,proto3" json:"passed_qc,omitempty"`
	Qc                    []*QCDecision          `protobuf:"bytes,11,rep,name=qc,proto3" json:"qc,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *Metadata) GetSceneSeed() string {
	if x != nil {
		return x.SceneSeed
	}
	return ""
}

func (x *Metadata) GetCreationTimestamp() int64 {
	if x != nil {
		return x.CreationTimestamp
	}
	return 0
}

func (x *Metadata) GetFiletype() string {
	if x != nil {
		return x.Filetype
	}
	return ""
}

func (x *Metadata) GetFilehandle() string {
	if x != nil {
		return x.Filehandle
	}
	return ""
}

func (x *Metadata) GetScanSeed() string {
	if x != nil {
		return x.ScanSeed
	}
	return ""
}

func (x *Metadata) GetScanFilehandle() string {
	if x != nil {
		return x.ScanFilehandle
	}
	return ""
}

func (x *Metadata) GetScanFiletype() string {
	if x != nil {
		return x.ScanFiletype
	}
	return ""
}

func (x *Metadata) GetScanCreationTimestamp() int64 {
	if x != nil {
		return x.ScanCreationTimestamp
	}
	return 0
}

func (x *Metadata) GetPassedQc() bool {
	if x != nil {
		return x.PassedQc
	}
	return false
}

func (x *Metadata) GetQc() []*QCDecision {
	if x != nil {
		return x.Qc
	}
	return nil
}

type QCDecision struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Decision          bool                   `protobuf:"varint,2,opt,name=decision,proto3" json:"decision,omitempty"`
	CreationTimestamp int64                  `protobuf:"varint,3,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	Note              string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	Data              string                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QCDecision) Reset() {
	*x = QCDecision{}
	mi := &file_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QCDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QCDecision) ProtoMessage() {}

func (x *QCDecision) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QCDecision.ProtoReflect.Descriptor instead.
func (*QCDecision) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *QCDecision) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QCDecision) GetDecision() bool {
	if x != nil {
		return x.Decision
	}
	return false
}

func (x *QCDecision) GetCreationTimestamp() int64 {
	if x != nil {
		return x.CreationTimestamp
	}
	return 0
}

func (x *QCDecision) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *QCDecision) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_metadata_proto protoreflect.FileDescriptor

const file_metadata_proto_rawDesc = "" +
	"\n" +
	"\x0emetadata.proto\x12\bmetadata\"\x8e\x03\n" +
	"\bMetadata\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\tR\x04seed\x12\x1d\n" +
	"\n" +
	"scene_seed\x18\x02 \x01(\tR\tsceneSeed\x12-\n" +
	"\x12creation_timestamp\x18\x03 \x01(\x03R\x11creationTimestamp\x12\x1a\n" +
	"\bfiletype\x18\x04 \x01(\tR\bfiletype\x12\x1e\n" +
	"\n" +
	"filehandle\x18\x05 \x01(\tR\n" +
	"filehandle\x12\x1b\n" +
	"\tscan_seed\x18\x06 \x01(\tR\bscanSeed\x12'\n" +
	"\x0fscan_filehandle\x18\a \x01(\tR\x0escanFilehandle\x12#\n" +
	"\rscan_filetype\x18\b \x01(\tR\fscanFiletype\x126\n" +
	"\x17scan_creation_timestamp\x18\t \x01(\x03R\x15scanCreationTimestamp\x12\x1b\n" +
	"\tpassed_qc\x18\n" +
	" \x01(\bR\bpassedQc\x12$\n" +
	"\x02qc\x18\v \x03(\v2\x14.metadata.QCDecisionR\x02qc\"\x93\x01\n" +
	"\n" +
	"QCDecision\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\bR\bdecision\x12-\n" +
	"\x12creation_timestamp\x18\x03 \x01(\x03R\x11creationTimestamp\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04dataB\x13Z\x11metadata/metadatab\x06proto3"

var (
	file_metadata_proto_rawDescOnce sync.Once
	file_metadata_proto_rawDescData []byte
)

func file_metadata_proto_rawDescGZIP() []byte {
	file_metadata_proto_rawDescOnce.Do(func() {
		file_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)))
	})
	return file_metadata_proto_rawDescData
}

var file_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metadata_proto_goTypes = []any{
	(*Metadata)(nil),   // 0: metadata.Metadata
	(*QCDecision)(nil), // 1: metadata.QCDecision
}
var file_metadata_proto_depIdxs = []int32{
	1, // 0: metadata.Metadata.qc:type_name -> metadata.QCDecision
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_metadata_proto_init() }
func file_metadata_proto_init() {
	if File_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metadata_proto_goTypes,
		DependencyIndexes: file_metadata_proto_depIdxs,
		MessageInfos:      file_metadata_proto_msgTypes,
	}.Build()
	File_metadata_proto = out.File
	file_metadata_proto_goTypes = nil
	file_metadata_proto_depIdxs = nil
}
