// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: seed.proto

package seed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Seed struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MasterSeed        string                 `protobuf:"bytes,1,opt,name=master_seed,json=masterSeed,proto3" json:"master_seed,omitempty"`
	Seed              string                 `protobuf:"bytes,2,opt,name=seed,proto3" json:"seed,omitempty"`
	CreationTimestamp int64                  `protobuf:"varint,3,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Seed) Reset() {
	*x = Seed{}
	mi := &file_seed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seed) ProtoMessage() {}

func (x *Seed) ProtoReflect() protoreflect.Message {
	mi := &file_seed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seed.ProtoReflect.Descriptor instead.
func (*Seed) Descriptor() ([]byte, []int) {
	return file_seed_proto_rawDescGZIP(), []int{0}
}

func (x *Seed) GetMasterSeed() string {
	if x != nil {
		return x.MasterSeed
	}
	return ""
}

func (x *Seed) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *Seed) GetCreationTimestamp() int64 {
	if x != nil {
		return x.CreationTimestamp
	}
	return 0
}

var File_seed_proto protoreflect.FileDescriptor

const file_seed_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"seed.proto\x12\x05seeds\"j\n" +
	"\x04Seed\x12\x1f\n" +
	"\vmaster_seed\x18\x01 \x01(\tR\n" +
	"masterSeed\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\tR\x04seed\x12-\n" +
	"\x12creation_timestamp\x18\x03 \x01(\x03R\x11creationTimestampB\fZ\n" +
	"seeds/seedb\x06proto3"

var (
	file_seed_proto_rawDescOnce sync.Once
	file_seed_proto_rawDescData []byte
)

func file_seed_proto_rawDescGZIP() []byte {
	file_seed_proto_rawDescOnce.Do(func() {
		file_seed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seed_proto_rawDesc), len(file_seed_proto_rawDesc)))
	})
	return file_seed_proto_rawDescData
}

var file_seed_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_seed_proto_goTypes = []any{
	(*Seed)(nil), // 0: seeds.Seed
}
var file_seed_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seed_proto_init() }
func file_seed_proto_init() {
	if File_seed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seed_proto_rawDesc), len(file_seed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_seed_proto_goTypes,
		DependencyIndexes: file_seed_proto_depIdxs,
		MessageInfos:      file_seed_proto_msgTypes,
	}.Build()
	File_seed_proto = out.File
	file_seed_proto_goTypes = nil
	file_seed_proto_depIdxs = nil
}
