import sys
import os
import random
import numpy as np
import mathutils.noise
import bpy  # might be flagged by IDE as error, dependency available at runtime
# Initialize the seeded random functions used within blender with a deterministic random value generated by the seed service

# seed the internal python prngs using the job seed


def patch_random(seed):
    random.seed(seed)
    np.random.seed(seed)
    mathutils.noise.seed_set(seed)

# read the job from stdin and parse it into parts


def read_job():
    line = sys.stdin.readline().strip()
    if not line:
        return None

    parts = line.split()
    if len(parts) != 4:
        print(f"ERROR: malformed job line: {line}", flush=True)
        return None

    if parts[0] != "JOB":
        print(f"ERROR: expected 'JOB', got: {parts[0]}", flush=True)
        return None

    # unpack fields
    _, output_file, worker_seed_str, seed = parts
    worker_seed = int(worker_seed_str)

    return output_file, worker_seed, seed


# the main function that executes user scripts using information from the jobs privided through stdin
if __name__ == '__main__':
    # Read input data from the args
    user_script_path = sys.argv[sys.argv.index("--f")+1]
    while True:  # repeat until death
        job = read_job()
        if job is None:
            continue

        outputFile, worker_seed, seed = job
        # seed prngs using worker seed
        patch_random(worker_seed)
        # ensure user script has access to job data if necessary
        wrapper_globals = {
            "__name__": "__main__",
            "__file__": user_script_path,
            "OUTPUT_FILE": outputFile
        }
        # load and run the user script from the specified path
        with open(user_script_path, 'r') as f:
            code = compile(f.read(), user_script_path, 'exec')
            exec(code, wrapper_globals)

        # After user script runs return a message signifying work completion and wait for next job
        print(f"RESULT {outputFile} {seed}", flush=True)
